baseURL = "https://cef.netlify.app/"
languageCode = "fr-be"
title = "CEF - Comité des Elèves Francophones"
Paginate = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    cloudinary_url = "https://res.cloudinary.com/cefasbl/image/upload/"

[taxonomies]
  # singulier = "pluriel"
  category = "categories"
  tag = "tags"
