baseURL = "https://cef.netlify.com/"
languageCode = "fr-be"
title = "CEF - Comité des Elèves Francophones"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
    author = "Studio Colibri"

[taxonomies]
  theme = "themes" # singulier = "pluriel"
  tag = "tags"