baseURL = "https://cef.netlify.com/"
languageCode = "fr-be"
title = "CEF - Comité des Elèves Francophones"

[params]
    description = "Description du CEF"
    author = "Studio Colibri"

[taxonomies]
  theme = "themes" # singulier = "pluriel"
  tag = "tags"