baseURL = "https://cef.netlify.com/"
languageCode = "fr-be"
title = "CEF - Comité des Elèves Francophones"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Studio Colibri"

[taxonomies]
  theme = "themes" # singulier = "pluriel"
  tag = "tags"