Paginate = 9
baseURL = "https://cef.netlify.app/"
languageCode = "fr-be"
title = "CEF | Comité des Elèves Francophones"
removePathAccents = true
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Actualités"
url = "/actualites-podcasts/"
weight = 3
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 6
[[menu.footer]]
name = "Rejoins-nous !"
url = "/rejoins-nous/"
weight = 5
[[menu.footer]]
name = "Tes droits"
url = "/tes-droits/"
weight = 4
[[menu.footer]]
name = "Le CEF"
url = "/presentation/"
weight = 2
[[menu.footer]]
name = "Accueil"
url = "/"
weight = 1
[[menu.main]]
name = "Fonctionnement"
parent = "cef"
url = "/fonctionnement/"
weight = 2
[[menu.main]]
name = "Positions"
parent = "cef"
url = "/positions/"
weight = 3
[[menu.main]]
name = "Présentation"
parent = "cef"
url = "/presentation/"
weight = 1
[[menu.main]]
name = "Actualités"
url = "/actualites-podcasts/"
weight = 2
[[menu.main]]
name = "Animations"
url = "/animations/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 6
[[menu.main]]
name = "Rejoins-nous !"
url = "/rejoins-nous/"
weight = 5
[[menu.main]]
name = "Tes droits"
url = "/tes-droits/"
weight = 4
[[menu.main]]
identifier = "cef"
name = "Le CEF"
url = "/presentation/"
weight = 1
[params]
cloudinary_url = "https://res.cloudinary.com/cefasbl/image/upload/"
[taxonomies]
category = "categories"
tag = "tags"
theme = "themes"
