baseURL = "https://cef.netlify.app/"
languageCode = "fr-be"
title = "CEF - Comité des Elèves Francophones"
Paginate = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Studio Colibri"

[taxonomies]
  # singulier = "pluriel"
  category = "categories"
  tag = "tags"
