[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/sass/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/fonts/*.woff2"
  [headers.values]
    Content-Type = "application/font-woff2"
    Cache-Control = "public, max-age=31536000"

[build]
publish = "public"
command = "hugo && gulp minify"

[context.production.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"