---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/main_nav.toml
  label: Menu principal
- type: document
  path: data/footer.toml
  label: Bas de page
- type: document
  path: data/infos.toml
  label: Informations générales
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/actualites-podcasts
  label: Actualites podcasts
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/cefasbl/image/upload/c_scale,dpr_auto,q_70,w_740,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
